---
title: "Adriel M. Sierra's CV"
author: "Adriel Sierra"
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
# set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
    css:
    - resume
    - https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css
#- <i class="fa fa-whatsapp"></i> +1 (581) 978-2494
knit: pagedown::chrome_print
---


---
```{r echo=FALSE}
#install.packages("fontawesome")
library(fontawesome)
```


Aside
================================================================================


Contact Info {#contact}
--------------------------------------------------------------------------------
- <i class="fa fa-envelope"></i> adriel-michel.sierra-pinilla.1@ulaval.ca; adsierra26@gmail.com
- <i class="ai ai-orcid-square"></i>[ORCID](https://orcid.org/0000-0001-9900-1350)
- <i class="fa fa-github"></i>[Github](https://github.com/adrielmsierra)
- <i class="ai ai-google-scholar-square"></i>[Google scholar](https://scholar.google.es/citations?user=8nlblCcAAAAJ&hl=es)
- <i class="ai ai-lattes-square"></i>[CNPq CV Lattes](http://lattes.cnpq.br/3414573361651865)


Skills {#skills}
--------------------------------------------------------------------------------

- Field work in terrestial habitats. Botany & Enthomology. 

- Experimental ecology and long term monitoring

- Molecular and chemical laboratory techniques

- Statistics in [R](https://www.r-project.org/)

- Bioinformatics - Unix-like

- Herbarium curator techniques

LANGUAGE {#skills}
--------------------------------------------------------------------------------

**Spanish** Native

**English** Fluent

**Portuguese** Fluent

**French** Intermediate


Main
================================================================================

Adriel M. Sierra {#title}
--------------------------------------------------------------------------------

### A Botanist interest in the ecology and conservation of tropical forest

RESEARCH FIELDS: Biodiversity. Botany. Conservation Biology. Disturbance Ecology. Ecology & Evolution. Microbial Ecology.

Current Appointment {data-concise=true}
--------------------------------------------------------------------------------

### Université Laval PhD. Student

Université Laval

Canada

2019 - 

- [Assessing habitat disturbance impacts on plant demography, genetic structure, and phyllosphere microbiota](http://villarreal-lab.ibis.ulaval.ca/team/adriel-m-sierra/)

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### PhD candidate, Biology

Université Laval

Québec, Canada

2019 - 

Supervisor: Juan Carlos Villarreal A.

### MSc Botany

Instituto Nacional de Pesquisas da Amazônia

Manaus, Brazil

2016 - 2018
 
Thesis: Metacommunity dynamics of epiphyllous bryophyte in fragmented forest in the Amazonian forest.

Supervisors: Charles E. Zartman & José J. Toledo

### BSc Biology, Minor in Plant Biology

Universidad de Panamá. 

Panama, Panama

2010 - 2015

Thesis: Comunidades de hepáticas epífilas (Marchantiophyta) sobre Piper grande 
vahl., en el P.N.G.D. Omar Torrijos H., El Copé.

Supervisors: Nayda Flores & Noris Salazar Allen 

Prior Research Positions {data-icon=share-alt}
--------------------------------------------------------------------------------
### Research collaborator

Amazon Fertilization Experiment (AFEX). Instituto Nacional de Pesquisas da Amazônia (INPA)

Manaus, Brazil

2018 - 2019

### Research collaborator

Long-Term Plot Monitoring Project in central Amazonia (PELD-MAUÁ). Instituto Nacional de Pesquisas da Amazônia (INPA)

Manaus, Brazil

2017 - 2018

### ELAP research Fellow

Université Laval. L'Institut de biologie intégrative et des systèmes (IBIS).

Québec, Canada

2018

### Graduate research fellow

Biological Dynamics of Forest Fragments Project (BDFFP)

Manaus, Brazil

2016 - 2017

### Research intern

Smithsonian Tropical Research Institute (STRI) 

Panama

2015 - 2016

Peer Reviewed Publications {data-icon=file #pubs}
--------------------------------------------------------------------------------
### Regional-level shift in epiphyllous bryophytes associated diazotroph community structure and diversity in an amazonian fragmented landscape

N/A

N/A

In prep

**Adriel M. Sierra**, Dennis O. Escolastico, Charles E. Zartman & Juan Carlos Villarreal A.

### Flood pulse disturbance shapes vertical and horizontal species richness patterns of epiphytic bryophytes in an Amazonian black-water forest

N/A

N/A

In prep

Charles E. Zartman, Adriano C. Quaresma, Maihyra M. Pombo, Gabriel M. Marcusso & **Adriel M. Sierra**

### Cyanobacteria detectability using the rbcL-X amplicon shows a reduced core microbiome in the coralloid roots of tropical gymnosperm 

Symbiosis

N/A

In revision

Sandrine Toupin, **Adriel M. Sierra**, Marta Alonso-García, Maycol Madrid, Noris Salazar Allen & Juan Carlos Villarreal A. 

### The consequences of mating system and dispersal potential on the genetic structure of leaf-inhabiting bryophyte metapopulations in a fragmented Amazonian landscape

Molecular Ecology [preprint](10.22541/au.168016508.89524249/v1)

N/A

In revision

**Adriel M. Sierra**, Marta Alonso-Garcia,  Charles E. Zartman & Juan Carlos Villarreal A.  

### Catalogue of liverworts (Marchantiophyta) and hornworts (Anthocerotophyta) from Central America and Cocos Island

Smithsonian Institution Scholarly Press

N/A

accepted

Gregorio Dauphin, Lars Söderström, Anders Hagborg, Noris Salazar Allen, **Adriel M. Sierra**, Tamás Pócs, José Gudiño L., Mervin E. Pérez, Juan Carlos Villarreal, Yarency Rodríguez, Matt von Konrat,  Alan Whittemore

### Phylogenomic time tree of bryophytes resolves 500 million years of diversification

[American Journal of Botany](https://doi.org/10.1002/ajb2.16249)

N/A

2023

Julia Bechteler, Gabriel Peñaloza-Bojacá, David Bell, Gordon Burleigh, Stuart F. McDaniel, Christine Davis, Emily Sessa, Alexander Bippus, Christine Cargill, Salut Chantanaorrapint, Isabel Draper, Gaik Ee Lee, Lorena Endara, Laura L. Forrest, Ricardo Garilleti, Sean Graham, Sanna Huttunen, Javier Jauregui Lazo, Francisco Lara, Juan Larraín, Lily Lewis, David Long, Dietmar Quandt, Karen S. Renzaglia, Alfons Schäfer-Verwimp, **Adriel M. Sierra**, Matt von Konrat, Charles Zartman, Bernard Goffinet, & Juan Carlos Villarreal A.

### A taxonomic review of the Amazonian rheophyte Schusterolejeunea (Spruce) Grolle (Lejeuneaceae: Cololejeuneinae), with two new combinations

[Cryptogamie, Bryologie 44(4):107-122](https://doi.org/10.5252/cryptogamie-bryologie2023v44a4)

N/A

2023

**Adriel M. Sierra** & Charles E. Zartman

### Historical biogeography of the austral hornwort genus Phaeomegaceros (Dendrocerotaceae, Anthocerotophyta

[Bryophyte Diversity and Evolution 45 (1): 44-66](https://doi.org/10.11646/bde.45.1.3)

N/A

2022

Gabriel Felipe Peñaloza-Bojacá, **Adriel M. Sierra**, Hannes Becher, Karen S. Renzaglia, Juan Carlos Villarreal A.  

### Bryophyte diversity and new species occurrences from Carauari in southwestern Amazonas, Brazil

[Pesquisas, Botânica 76: 263-271](https://www.anchietano.unisinos.br/publicacoes/botanica/volumes/076/76_012.pdf)

N/A

2022

Marta Regina Pereira, Francisca Andriele Nascimento da Silva, Jair Max Fortunato Maia, Ana Sofia Sousa de Holanda & **Adriel M. Sierra**

### A comparative study of temporal variation of two epiphytic bryophytes in a central Amazonian white-sand forest, Brazil

[Hoehnea 48: e1352020](https://doi.org/10.1590/2236-8906-135/2020)

N/A

2021

Marta R. Pereira, **Adriel M. Sierra**, Jair Max Furtunato Maia & Ana Sofia Sousa de Holanda

### Unveiled diversity: Amazonian Campinaranas harbor twice the number of bryophyte species recorded in the last century

[Acta Botanica Brasilica 35: 1-14](https://doi.org/10.1590/0102-33062020abb0428)

N/A

2021

Gabriela Ramos Cerqueira, **Adriel M. Sierra**, Anna Luiza Ilkiu-Borges, Sylvia Mota-de-Oliveira & Charles E. Zartman

### Two new species of Ceratolejeunea (Lejeuneaceae) and five noteworthy records for Brazil

[Bryophyte Diversity and Evolution 44:12-21](https://doi.org/10.11646/bde.44.1.2)

N/A

2021

**Adriel M. Sierra**, Cid José Passos Bastos & Charles E. Zartman

### Synopsis of the genus Pycnolejeunea (Spruce) Schiffn. (Lejeuneaceae, Marchantiophyta) in Brazil

[Hoehnea 47: e1132019](https://doi.org/10.1590/2236-8906-113/2019)

N/A

2020

Cid José Passos Bastos, Adriele Lima Gentil, **Adriel M. Sierra** & Charles E. Zartman

### Are extinction debts reflected in temporal changes of life history trait profiles? A fifteen-year reappraisal of bryophyte metacommunities in a fragmented landscape

[Biological Conservation 238: 108-218](https://doi.org/10.1016/j.biocon.2019.108218)

N/A

2019

**Adriel M. Sierra**, José J. Toledo, Henrique E. Nascimento, Marta R. Pereira & Charles E. Zartman

### Drepanolejeunea robinsonii (Lejeuneaceae: Drepanolejeuneinae), a new epiphyllous species from the Amazon forest

[The Bryologist 122: 292–296](https://doi.org/10.1639/0007-2745-122.2.292)

N/A

2019

Charles E. Zartman, **Adriel M. Sierra** & Rui-Liang Zhu.

### Advances in Calymperaceae (Dicranidae, Bryophyta) infra-familial phylogenetic relationships, geographical origin and divergence times 

[The Bryologist 122: 183–196](https://doi.org/10.1639/0007-2745-122.2.183)

N/A

2019

Marta R. Pereira, Paulo E. A. S. Câmara, Bruno S. Amorim, Stuart McDaniel, Adam Payton, Sarah B. Carey, **Adriel M. Sierra** & Charles E. Zartman

###  Contribution to the Bryophyte flora of Brazil: new country and state records from Amazonia 

[Rodriguésia 70: 1–9](https://doi.org/10.1590/2175-7860201970013) 

N/A

2019

**Adriel M. Sierra**, Marta R. Pereira & Charles E. Zartman

###  Reproductive traits as predictors of assembly chronosequence patterns in epiphyllous bryophyte metacommunities 
[Journal of Ecology 107(2): 875-886](http://doi.org/10.1111/1365-2745.13058)

N/A

2019

**Adriel M. Sierra**, José Julio Toledo, Noris Salazar Allen & Charles E. Zartman

::: aside
[**Shortlisted for the Harper Prize 2019**](https://jecologyblog.com/2020/02/26/2019-harper-prize-shortlist/)
:::

### Divergence time analyses suggest a Miocene origin of the narrow Amazonian endemic rheophytic Ceratolejeunea temnantha (Spruce) Reiner-Drehwald (Porellales, Lejeuneaceae)

[Bryophyte Diversity and Evolution 40: 55–67](http://doi.org/10.11646/bde.40.2.4)

N/A

2018

**Adriel M. Sierra**, Julia Bechteler, Domingos Cardoso, Charles E. Zartman & Juan Carlos Villarreal

### Bryophytes of Jaú National Park (Amazonas, Brazil): Estimating detectability and species richness in a lowland amazonian megareserve

[The Bryologist 121: 571–588](https://doi.org/10.1639/0007-2745-121.4.571)

N/A

2018

**Adriel M. Sierra**, Alain Vanderpoorten, Robbert S. Gradstein, Marta R. Pereira, Cid José Passos Bastos & Charles E. Zartman

### From the Guiana Highlands to the Brazilian Atlantic Rain Forest: four new species of Selaginella (Selaginellaceae Lycopodiophyta: S. agioneuma, S. magnafornensis, S. ventricosa, and S. zartmanii)

[PeerJ 6:e4708](http://doi.org/10.7717/peerj.4708)

N/A

2018

Iván A. Valdespino, Christian A. López, **Adriel M. Sierra** & Jorge Ceballos

### Three new species of Cheilolejeunea (Spruce) Steph. (Marchantiophyta, Lejeuneaceae) from northern Brazil 

[Phytotaxa 277 (1): 036-046](https://doi.org/10.11646/phytotaxa.277.1.3 )

N/A

2016

Cid José Passos Bastos, **Adriel M. Sierra** & Charles E. Zartman

### Notes on the genus Cololejeunea (Lejeuneaceae) in Panama. C. cingens (New Record) and C. tamasii 

[Polish Botanical Journal 61(2): 231-235](https://doi.org/10.1515/pbj-2016-0027)

N/A

2016

**Adriel M Sierra** & Gregorio Dauphin

### Adiciones de especies de hepáticas (Marchantiophyta) para la flora de Panamá II 
[Brenesia 83-84: 16-21]()

N/A

2015

Gregorio Dauphin, Noris Salazar Allen, José A. Gudiño L., **Adriel Sierra** & Deisi Reyes

### Leaf traits and herbivory levels in a tropical gymnosperm, Zamia stevensonii (Zamiaceae)

[American Journal of Botany 101(3):1-11](https://doi.org/10.3732/ajb.1300337)

N/A

2014

Alberto Prado, **Adriel Sierra**, Donald Windsor, & Jacqueline C. Bede

RESEARCH GRANTS {data-icon=award}
--------------------------------------------------------------------------------
### NSERC CREATE in Biodiversity, Ecosystem Services and Sustainability (BESS). USD$28 000.00

Phyllosphere microbiome

Québec, Canada

2019 - 2021


### Bequests Fund for research grant. USD$1 100.00 

Population genomics of epiphyllous bryophyte

British Bryological Society, UK

2018


### Emerging Leaders in the Americas Program. USD$8 000.00

Metapopulation genomics of epiphyllous bryophyte in fragmented forest 

Université Laval, Canada 

2018

### Thomas Lovejoy Research Support Program, Biological Dynamics of Forest Fragments Project. USD$4 000.00

Forest fragmentation effects on metacommunity dynamics of epiphyllous bryophyte 

Manaus, Brazil

2016 - 2017

SCHOLARSHIPS {data-icon=award}
--------------------------------------------------------------------------------
### Faculté des sciences et de génie, Université Laval. USD$28 000.00

PhD scholarship

Québec, Canada

2019 - 2022

### Bourse de formation à la recherche (Mitacs). USD$4 800.00

Évaluation des effets de Sauvetage Démographique, Génétique et Microbien des Gymnospermes Ménacées 

Québec, Canada

2020
	
### Emerging Leaders in the Americas Program. USD$4 700.00

Student academic exchange.

Ottawa, Canada

2018

### Coordenação de Aperfeiçoamento de Pessoal de Nível Superior (CAPES) – Brasil. USD$12 000.00

Master scholarship 

Brazil

2016 - 2018

### SENACYT & Smithsonian Tropical Research Institute (STRI). USD$4 000.00 

Research Experience for Undergraduates (REU) program

Panama

2015


### Natural History Museum, UK & NERC Science of the Environment.

Taxonomic principles and tools in botanic research. Full course scholarship plus daily subsistence of USD$150.00

United Kingdom

2015

### Eagle Hill Institute, Maine USA. 

Full Scholarship to participate in four courses in the Eagle Hill Institute.

Maine, United States of America

2013

### University of Winconsin-Green Bay & Smithsonian Tropical Research Institute (STRI). 

Full Scholarship to participate in the Tropical Ecology course 

Panama

2012

AWARDS  {data-icon=award}
--------------------------------------------------------------------------------
### Faculté des sciences et de génie, Université Laval.

Doctoral Accomplishment Scholarship

Québec, Canada

2019-2023

USD$6000.00

###	Instituto de Ecología y Biodiversidad de Chile-Magallanes. International Association of Bryologist Conference. 

Travel Award 

N/A

2015

US$500.00

### Corredor Biológico Mesoamericano del Atlántico Panameño (CBMAP II). 

Travel Award 

N/A

2015

US$1 350.00

###	Universidad de Panamá. Vicerectoría of Student Affairs (VAE). 

Travel Award

N/A

2013

US$667.40

### Corredor Biológico Mesoamericano del Atlántico Panameño (CBMAP II).

Travel Award

N/A

2013

US$600.00

TEACHING EXPERIENCE {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Substitute Professor

Universidade Estadual de Amazonas (UEA)

São Gabriel da Cachoeira, Brazil

2018

Plant Physiology for students of Bachelor degree in Biological Science

### Course instructur 

Instituto Nacional de Pesquisa Amazónica (INPA)

Manaus, Brazil

2016

Introduction to bryophyte identification (General Characteristics, Systematic, Morphology, reproduction and geographic occurrence)

###	Guest lecture and laboratory practice

Universidad de Panamá   

Panama

2014

Systematics of seedless plants (BIO 314 Botánica Sistematica I) 


CONSULTANT WORK {data-icon=suitcase}
--------------------------------------------------------------------------------
### Flora diversity baseline of the National Parks in Panama

Corredor Biológico Mesoamericano del Atlántico Panameño (CBMAP II). National System of Monitoring and Information of the Biological Diversity (SNMIDB). 

Panama, Panama

2012 - 2015


### Plant diversity in remnants forest patches 

Corredor Biológico Mesoamericano del Atlántico Panameño (CBMAP II)

Capira, Panama

2014


TECHNICAL ASSISTANSHIP {data-icon=suitcase}
--------------------------------------------------------------------------------

### Museum collection curator assistant

Natural History Museum of Panama. 

Panama

2014

### Geo-referencing environmental investments

Corredor Biológico Mesoamericano del Atlántico Panameño (CBMAPII)

Panama

2012 - 2013

### Herbarium assistant 

Herbarium of Panama (PMA). University of Panama.

Panama

2011 - 2013

TERRESTIAL FIELD EXPERIENCE {data-icon=compass}
--------------------------------------------------------------------------------

### Botanical and Ecological Survey

Bryophytes (Liverwort, Mosses and hornworts), Cycads (Zamia), Angiosperm

Panama 

2011 -

### Entomological survey

General insect collection

Panama

2011 - 2015

### Botanical and Ecological Survey

Bryophytes (Liverwort, Mosses and hornworts), Angiosperm (Humiriaceae, Arecaceae)

Brazil (Amazon forest & Guyana highlands) 

2016 - 2019

### Bryophyte survey in Patagonia

N/A

Chile (Navarino Island) 

2015

### Bryophyte survey in temperate forest

N/A

United States, Maine

2013

CONFERENCE PRESENTATIONS {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Génétique de l'hôte et microbiote diazotrophe associé des bryophytes foliaires dans un paysage amazonien fragmenté expérimentalement. 

16e Colloque du CEF. Québec, Canada. [Poster](https://www.cef-cfr.ca/uploads/Colloque/Colloque2023_Affiche_AdrielMSierra.pdf)

N/A

2023

### Impactos da fragmentação na Floresta Amazônica: sobre a biodiversidade de Briófitas epífilas. 

1o Encontro de Briólogos Online e 4 Simpósio de Briófitas do Brasil. [Oral presntation](https://www.youtube.com/watch?v=iiQgqvGfG-s)

N/A

2022

### Forest fragmentation impacts on biodiversity of epiphyllous bryophytes in the Amazon. 

Séminaire de mi-parcours. Université Laval.

N/A

2021

### Changes in population size and genetic structure of epiphyllous bryophytes in Amazonian Forest fragments. 

BESS-McGill symposium (Oral presntation)

N/A

2021

### Changements dans la taille de la population et la structure génétique des bryophytes épiphylles dans les fragments de forêt amazonienne. 

11e édition 2.0 du Colloque du Département de Biologie, Université Laval (Oral presntation)

N/A

2021

### The plight of plants in light of deforestation in the Amazon: insights from epiphyllous metacommunity dynamics. 

Bryophytes, lichens, and northern ecosystems in a changing world BL2021 (Oral presntation)

N/A

2021

### Microbiome role on the species assembly of diverse epiphyllous metacommunities. 

BESS-McGill 2019 symposium (Oral presntation)

N/A

2019

### Briófitas del bosque amazónico 

Universidad de Panamá. Panamá, Panamá. (Invited speaker)

N/A
 
2019

### Briófitas no margem da floresta Amazônica 

Universidade Federal da Bahia (UFBA). Salvador, Brazil. (Invited speaker)

N/A

2019

### Sucesión ecológica en hábitats efímeros: Trayectorias divergentes en comunidades de briofitas epífilas sugieren que no hay una dinámica sucesional. 

XXVII Congreso Científico Nacional, Universidad de Panamá. (Oral presntation)

N/A

2015

### Epiphyllous liverworts on the understory shrub, Piper grande Vahl., in the National Park G. D. Omar Torrijos H., El Copé (Panamá). Advance report. 

International Association of Bryologist (IAB), Puerto Williams, Chile. (Oral presntation)

N/A

2015

### Diversidad Florística en las turberas de Schoodic Point, Acadia National Park. Maine USA. 

XXVI Congreso Científico Nacional, Universidad de Panamá. (Poster)

N/A

2013

::: aside
#### PROFESSIONAL SOCIETIES

-British Ecological Society

-American Genetic Association

-International Association of Bryologists

-The Cycad Society

-American Bryological and Lichenological Society
:::

SCIENTIFIC BLOG POSTS {data-icon=file #pubs}
--------------------------------------------------------------------------------

### A question of a century in ecology leading to applied forest restoration and ecosystem services 

[STRI's Tropical Biology Field Course Blog](https://strineoigert.wordpress.com/2020/01/25/a-question-of-a-century-in-ecology-leading-to-applied-forest-restoration-and-ecosystem-service/)

N/A

2020

### Illustrating tropical forest cryptic organisms 

[STRI's Tropical Biology Field Course Blog](https://strineoigert.wordpress.com/2020/02/16/illustrating-tropical-forest-cryptic-organisms/)

N/A

2020

### Bats economic services

[STRI's Tropical Biology Field Course Blog](https://strineoigert.wordpress.com/2020/02/19/bats-economic-services/)
 
N/A

2020

### Night sky over Coibita

[STRI's Tropical Biology Field Course Blog](https://strineoigert.wordpress.com/2020/02/20/night-sky-over-coibita/)

N/A

2020

ACADEMIC AND SOCIAL INVOLVEMENT {data-icon="fad fa-users"}
--------------------------------------------------------------------------------
### Student Committee

[L'Institut de biologie intégrative et des systèmes (IBIS), Université Laval](http://www.ibis.ulaval.ca/activites/). Co-president since 2023

Québec, Canada

2021 - 

### Scientific outreach of Latin American Bryophytes

[Briofitas Latinoamerica](https://www.facebook.com/BriofitasLatinoamerica)

N/A

2022 - 

### Academic and social integration program at the University Laval

[Programme de jumelage, Université Laval](https://www.bve.ulaval.ca/etudiants-etrangers/programme-de-jumelage/devenir-parrain-marraine/)

Québec, Canada

2021 - 2022

### Botanical Illustration Group

Instituto Nacional de Pesquisa Amazónica (INPA) herbarium

Manaus, Brazil

2018 - 2019

### Scientific outreach activities

Instituto Nacional de Pesquisa Amazónica (INPA) & Universidade Estadual de Amazonas (UEA)

Manaus, Brazil

2016 - 2019


Disclaimer {#disclaimer style="width: var(--sidebar-width); padding-left: var(--sidebar-horizontal-padding);"}
--------------------------------------------------------------------------------
